python_sources = [
  '__init__.py',
  'constants.py',
  'engine.py',
  'io.py',
  'mixture_model.py',
  'parameter_space.py',
  'presets.py',
  'priors.py',
  'rejection.py',
  'result.py',
  'samplers.py',
  'transforms.py',
]

py3.install_sources(
  python_sources,
  subdir: 'cosmic/sample/stroopwafel'
)