C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.23.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitrand1(setupfunc)
      external setupfunc
      integer idum1
      common /rand1/ idum1
      call setupfunc(idum1)
      end

      subroutine f2pyinitrand2(setupfunc)
      external setupfunc
      integer idum2
      integer iy
      integer ir(32)
      common /rand2/ idum2,iy,ir
      call setupfunc(idum2,iy,ir)
      end

      subroutine f2pyinittypes(setupfunc)
      external setupfunc
      integer ktype(15,15)
      common /types/ ktype
      call setupfunc(ktype)
      end

      subroutine f2pyinitflags(setupfunc)
      external setupfunc
      integer tflag
      integer ifflag
      integer remnantflag
      integer wdflag
      integer bhflag
      integer windflag
      integer qcflag
      integer eddlimflag
      integer bhspinflag
      integer aic
      integer rejuvflag
      integer htpmb
      integer st_cr
      integer st_tide
      integer bdecayfac
      integer grflag
      integer bhms_coll_flag
      common /flags/ tflag,ifflag,remnantflag,wdflag,bhflag,windfl
     &ag,qcflag,eddlimflag,bhspinflag,aic,rejuvflag,htpmb,st_cr,st_tide,
     &bdecayfac,grflag,bhms_coll_flag
      call setupfunc(tflag,ifflag,remnantflag,wdflag,bhflag,windfl
     &ag,qcflag,eddlimflag,bhspinflag,aic,rejuvflag,htpmb,st_cr,st_tide,
     &bdecayfac,grflag,bhms_coll_flag)
      end

      subroutine f2pyinitmtvars(setupfunc)
      external setupfunc
      real*8 don_lim
      real*8 acc_lim
      real*8 mbh_initial
      common /mtvars/ don_lim,acc_lim,mbh_initial
      call setupfunc(don_lim,acc_lim,mbh_initial)
      end

      subroutine f2pyinitceflags(setupfunc)
      external setupfunc
      integer ceflag
      integer cekickflag
      integer cemergeflag
      integer cehestarflag
      integer ussn
      common /ceflags/ ceflag,cekickflag,cemergeflag,cehestarflag,
     &ussn
      call setupfunc(ceflag,cekickflag,cemergeflag,cehestarflag,us
     &sn)
      end

      subroutine f2pyinittrackers(setupfunc)
      external setupfunc
      integer pisn_track(2)
      common /trackers/ pisn_track
      call setupfunc(pisn_track)
      end

      subroutine f2pyinitmetvars(setupfunc)
      external setupfunc
      real*8 zsun
      common /metvars/ zsun
      call setupfunc(zsun)
      end

      subroutine f2pyinitwindvars(setupfunc)
      external setupfunc
      real*8 neta
      real*8 bwind
      real*8 hewind
      real*8 beta
      real*8 xi
      real*8 acc2
      real*8 epsnov
      real*8 eddfac
      real*8 gamma
      common /windvars/ neta,bwind,hewind,beta,xi,acc2,epsnov,eddf
     &ac,gamma
      call setupfunc(neta,bwind,hewind,beta,xi,acc2,epsnov,eddfac,
     &gamma)
      end

      subroutine f2pyinitcevars(setupfunc)
      external setupfunc
      real*8 qcrit_array(16)
      real*8 alpha1
      real*8 lambdaf
      common /cevars/ qcrit_array,alpha1,lambdaf
      call setupfunc(qcrit_array,alpha1,lambdaf)
      end

      subroutine f2pyinitmagvars(setupfunc)
      external setupfunc
      real*8 bconst
      real*8 ck
      common /magvars/ bconst,ck
      call setupfunc(bconst,ck)
      end

      subroutine f2pyinitsnvars(setupfunc)
      external setupfunc
      real*8 natal_kick_array(2,5)
      real*8 sigma
      real*8 sigmadiv
      real*8 bhsigmafrac
      real*8 polar_kick_angle
      real*8 pisn
      real*8 ecsn
      real*8 ecsn_mlow
      real*8 bhspinmag
      real*8 mxns
      real*8 rembar_massloss
      integer kickflag
      common /snvars/ natal_kick_array,sigma,sigmadiv,bhsigmafrac,
     &polar_kick_angle,pisn,ecsn,ecsn_mlow,bhspinmag,mxns,rembar_masslos
     &s,kickflag
      call setupfunc(natal_kick_array,sigma,sigmadiv,bhsigmafrac,p
     &olar_kick_angle,pisn,ecsn,ecsn_mlow,bhspinmag,mxns,rembar_massloss
     &,kickflag)
      end

      subroutine f2pyinittidalvars(setupfunc)
      external setupfunc
      real*8 fprimc_array(16)
      common /tidalvars/ fprimc_array
      call setupfunc(fprimc_array)
      end

      subroutine f2pyinitmixvars(setupfunc)
      external setupfunc
      real*8 rejuv_fac
      common /mixvars/ rejuv_fac
      call setupfunc(rejuv_fac)
      end

      subroutine f2pyinitcmcpass(setupfunc)
      external setupfunc
      real*8 merger
      integer*8 id1_pass
      integer*8 id2_pass
      integer*8 using_cmc
      common /cmcpass/ merger,id1_pass,id2_pass,using_cmc
      call setupfunc(merger,id1_pass,id2_pass,using_cmc)
      end

      subroutine f2pyinitpoints(setupfunc)
      external setupfunc
      real*8 pts1
      real*8 pts2
      real*8 pts3
      common /points/ pts1,pts2,pts3
      call setupfunc(pts1,pts2,pts3)
      end

      subroutine f2pyinittstepc(setupfunc)
      external setupfunc
      real*8 dmmax
      real*8 drmax
      common /tstepc/ dmmax,drmax
      call setupfunc(dmmax,drmax)
      end

      subroutine f2pyinitsingle(setupfunc)
      external setupfunc
      real*8 scm(50000,14)
      real*8 spp(20,3)
      common /single/ scm,spp
      call setupfunc(scm,spp)
      end

      subroutine f2pyinitbinary(setupfunc)
      external setupfunc
      real*8 bcm(50000,38)
      real*8 bpp(1000,43)
      common /binary/ bcm,bpp
      call setupfunc(bcm,bpp)
      end

      subroutine f2pyinitcheckstate_params(setupfunc)
      external setupfunc
      real*8 dtp_state(15)
      common /checkstate_params/ dtp_state
      call setupfunc(dtp_state)
      end

      subroutine f2pyinitcheckstate_array(setupfunc)
      external setupfunc
      real*8 checkstate_array(15,123)
      common /checkstate_array/ checkstate_array
      call setupfunc(checkstate_array)
      end

      subroutine f2pyinitcheck_dtp(setupfunc)
      external setupfunc
      integer check_dtp
      common /check_dtp/ check_dtp
      call setupfunc(check_dtp)
      end

      subroutine f2pyinitfall(setupfunc)
      external setupfunc
      real*8 fallback
      common /fall/ fallback
      call setupfunc(fallback)
      end


